### DISCUSSION TITLE
Action is stuck

### DISCUSSION THREAD

**Discussion by IlyaSemenov** [cycjimmy/semantic-release-action#71] [Q&A] [answered]
The action is stuck, can you please advise what I made wrong?

<img width="1534" alt="Screenshot 2021-06-23 at 21 30 10" src="https://user-images.githubusercontent.com/128121/123115476-543f7980-d46a-11eb-9f82-91794873cc5c.png">

Here's the workflow file:

https://github.com/IlyaSemenov/node-data-cleaner/blob/4eb2505c9d94c28e5927ec3d92e5c2bb08b1482c/.github/workflows/release.yml

```yml
name: Release
on:
  push:
    branches:
      - master
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: c-hive/gha-yarn-cache@v2
      - run: yarn --frozen-lockfile
      - run: yarn build
      - run: yarn test
      - uses: cycjimmy/semantic-release-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
```

the new library version was successfully published on npm but then it all stuck.
