### DISCUSSION TITLE
How to skip npm release, and only generate tags

### DISCUSSION THREAD

**Discussion by jpbnetley** [cycjimmy/semantic-release-action#98] [Q&A] [answered]
Hi, 
I am using this acton to manage releases for a Github composite action.

I configured the action with the following
```
- name: Semantic Release
        uses: cycjimmy/semantic-release-action@v3
        id: semantic
        with:
          branch: 'main'
          extra_plugins: |
            @semantic-release/commit-analyzer
            @semantic-release/release-notes-generator
            @semantic-release/git
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

I was under the impression if I specify the plugins for the action with `extra_plugins`, they will override the default plugins.

Ie I don't want to do the npm release part, but I want to do the commit-analyzer, release-notes-generator, git
to publish a new tag, and not release it to npm.

But I see the plugins doesn't seem to override, as seen in the build log.

```
[9:49:06 AM] [semantic-release] › ℹ  Running semantic-release version 19.0.2
[9:49:06 AM] [semantic-release] › ✔  Loaded plugin "verifyConditions" from "@semantic-release/npm"
[9:49:06 AM] [semantic-release] › ✔  Loaded plugin "verifyConditions" from "@semantic-release/github"
[9:49:06 AM] [semantic-release] › ✔  Loaded plugin "analyzeCommits" from "@semantic-release/commit-analyzer"
[9:49:06 AM] [semantic-release] › ✔  Loaded plugin "generateNotes" from "@semantic-release/release-notes-generator"
[9:49:06 AM] [semantic-release] › ✔  Loaded plugin "prepare" from "@semantic-release/npm"
[9:49:06 AM] [semantic-release] › ✔  Loaded plugin "publish" from "@semantic-release/npm"
[9:49:06 AM] [semantic-release] › ✔  Loaded plugin "publish" from "@semantic-release/github"
[9:49:06 AM] [semantic-release] › ✔  Loaded plugin "addChannel" from "@semantic-release/npm"
[9:49:06 AM] [semantic-release] › ✔  Loaded plugin "addChannel" from "@semantic-release/github"
[9:49:06 AM] [semantic-release] › ✔  Loaded plugin "success" from "@semantic-release/github"
[9:49:06 AM] [semantic-release] › ✔  Loaded plugin "fail" from "@semantic-release/github"
[9:49:08 AM] [semantic-release] › ✔  Run automated release from branch main on repository https://x-access-token:[secure]@github.com/fullfacing/ff-web-release-package.git
[9:49:08 AM] [semantic-release] › ✔  Allowed to push to the Git repository
[9:49:08 AM] [semantic-release] › ℹ  Start step "verifyConditions" of plugin "@semantic-release/npm"
[9:49:08 AM] [semantic-release] [@semantic-release/npm] › ℹ  Verify authentication for registry https://npm.pkg.github.com
[9:49:08 AM] [semantic-release] › ✖  Failed step "verifyConditions" of plugin "@semantic-release/npm"
[9:49:08 AM] [semantic-release] › ℹ  Start step "verifyConditions" of plugin "@semantic-release/github"
[9:49:08 AM] [semantic-release] [@semantic-release/github] › ℹ  Verify GitHub authentication (https://api.github.com)
[9:49:08 AM] [semantic-release] › ✔  Completed step "verifyConditions" of plugin "@semantic-release/github"
[9:49:08 AM] [semantic-release] › ℹ  Start step "fail" of plugin "@semantic-release/github"
[9:49:09 AM] [semantic-release] [@semantic-release/github] › ℹ  Found existing semantic-release issue #2.
[9:49:11 AM] [semantic-release] [@semantic-release/github] › ℹ  Added comment to issue #2: https://github.com/fullfacing/ff-web-release-package/issues/2#issuecomment-1066578[47](https://github.com/fullfacing/ff-web-release-package/runs/5535085207?check_suite_focus=true#step:3:47)2.
[9:49:11 AM] [semantic-release] › ✔  Completed step "fail" of plugin "@semantic-release/github"
[9:49:11 AM] [semantic-release] › ✖  ENONPMTOKEN No npm token specified.
An npm token (https://github.com/semantic-release/npm/blob/master/README.md#npm-registry-authentication) must be created and set in the NPM_TOKEN environment variable on your CI environment.
```

Is there a way that I can complete the action when it gets to the tagging step, and then skip the npm release step and finish up the action?

Thanks for the awesome action and docs :) 

I created the original discussion here: https://github.com/semantic-release/semantic-release/discussions/2392
but I think this may be action spesific.

**Comment by jpbnetley** [comment, marked as answer]
I added the releaserc file and spesified the plugins there as well.
Works perfectly now. :)

**Reply by IGZangelcostales** [reply]
hello @jpbnetley ! I'm a novice with this. I want to use semantic-release for only creating tags and not releases, I'm working with GitLab, so my context is a little different. but can you explain to me how you do it?

Many thanks for considering my request.

**Reply by jpbnetley** [reply]
Hi @IGZangelcostales 
The goal I was after, was creating git tags, and github release notes. 
(To omit the release notes, you can probably just exclude these 2 plugins: 
`"@semantic-release/release-notes-generator", "@semantic-release/github"`)

I am not sure about GitLab, but for GitHub I did the following.
In the root of the project I added a `.releaserc.json`,
where the file contents looked like the following:
```js
{
  "plugins": [
    "@semantic-release/commit-analyzer",
    "@semantic-release/release-notes-generator",
    "@semantic-release/github",
    "@semantic-release/git"
  ]
}
```

Then for my GitHub action, I also specified the plugins:
```yml
- name: Semantic Release
        uses: cycjimmy/semantic-release-action@v3
        id: semantic
        with:
          branch: 'main'
          extra_plugins: |
            @semantic-release/commit-analyzer
            @semantic-release/release-notes-generator
            @semantic-release/github
            @semantic-release/git
```

Note that the plugins specified in the `GitHub action` and the `releaserc.json` file matches.

That should be it.
Now when the action runs, it checks the commits to see what version it should bump to, then creates the appropriate tag, and generates the release notes.

I hope this helps :)

**Reply by bombillazo** [reply]
How do you set so the `releaserc` so the process does NOT create a release, but does create the tag?

`"@semantic-release/github"` by default creates a Release

**Reply by jpbnetley** [reply]
> How do you set so the `releaserc` so the process does NOT create a release, but does create the tag?
> 
> `"@semantic-release/github"` by default creates a Release

@bombillazo  I would guess something like this.
for the file `.releaserc.json`
```json
{
  "plugins": [
    "@semantic-release/commit-analyzer",
    "@semantic-release/git"
  ]
}
```

for the github action example
```yml
- name: Semantic Release
        uses: cycjimmy/semantic-release-action@v3
        id: semantic
        with:
          branch: 'main'
          extra_plugins: |
            @semantic-release/commit-analyzer
            @semantic-release/git
```
