### ISSUE TITLE
Output new_release_published does not return a truthy value?

### ISSUE THREAD

**Issue by erzz** [cycjimmy/semantic-release-action#104]
**Describe the bug**
I have a job dependent on a release being created - and it always runs even if there was no release created. So i dug into it a bit and added an echo of the output in the dependent jobwhich appears correct:

results of echo from a couple of runs with/without release:

```
release created? = true # after a release was created
release created? = false # after a release was not created
```

However if I make the dependent job run only based on it returning a truthy value it always runs

```yaml
  floating-tag:
    name: Create floating tag
    needs: release
    if: ${{ needs.release.outputs.new_release_published }}
    runs-on: ubuntu-latest
    steps:
      - etc etc
```

The floating-tag job runs every time - despite the following outcome from semantic-release

```
[7:51:54 AM] [semantic-release] › ℹ  Found git tag v1.0.5 associated with version 1.0.5 on branch main
[7:51:54 AM] [semantic-release] › ℹ  Found 0 commits since last release
[7:51:54 AM] [semantic-release] › ℹ  Start step "analyzeCommits" of plugin "@semantic-release/commit-analyzer"
[7:51:54 AM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  Analysis of 0 commits complete: no release
[7:51:54 AM] [semantic-release] › ✔  Completed step "analyzeCommits" of plugin "@semantic-release/commit-analyzer"
[7:51:54 AM] [semantic-release] › ℹ  There are no relevant changes, so no new version is released.
```

If I use string comparison instead then the results are as expected.

```yaml
  floating-tag:
    name: Create floating tag
    needs: release
    if: ${{ needs.release.outputs.new_release_published == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - etc etc
```
