### ISSUE TITLE
Execute Semantic Release without a package.json file

### ISSUE THREAD

**Issue by maxiride** [cycjimmy/semantic-release-action#115]
It is my understanding that the action can feed the underlying semantic release with options by using the `with` fields `branches`, `extra_plugins` etc. Hence, executing semantic release **without** a package.json **and without** a `.releaserc` file for non-javascript projects.

**Describe the bug**

The action extis with the following error:

```
AggregateError: 
    SemanticReleaseError: Missing `package.json` file.
        at module.exports (/home/runner/work/_actions/cycjimmy/semantic-release-action/v2/node_modules/@semantic-release/npm/lib/get-error.js:6:10)
        at module.exports (/home/runner/work/_actions/cycjimmy/semantic-release-action/v2/node_modules/@semantic-release/npm/lib/get-pkg.js:17:33)
```

**Workflow**
```yml
on:
  push:
    branches:
      - main
      - beta

jobs:
  release:
    name: Semantic Release
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Execute Semantic Release
        id: semantic
        uses: cycjimmy/semantic-release-action@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          semantic_version: 19
          branches: |
            [
              "+([0-9])?(.{+([0-9]),x}).x",
              "main",
              {
                "name": "beta",
                "prerelease": true
              }
            ]
          extra_plugins: |
            "@semantic-release/commit-analyzer"
            "@semantic-release/release-notes-generator"
            "@semantic-release/github"
```

**Expected behavior**
I expect the semantic release to run.

**Additional context**
The action docs [states](https://github.com/cycjimmy/semantic-release-action#branches) `branches will override the branches attribute in your configuration file. `, so I've also tried to execute the action with an empty .releaserc file guessing it would have been populated by the action. Same error result.

Am I misunderstanding the action use or is there an error in my configuration?

**Comment by mnarra-varmour** [comment]
+1 
 facing same issue

**Comment by cordelou** [comment]
+1

**Comment by olambdao** [comment]
+1

**Comment by bhchew** [comment]
having the same issue, seem this happens regardless the repo is a node project.

Was having the same thought if we are missing some config in the workflow?

**Comment by patrickserrano** [comment]
Also running into this, has anyone sorted it out?

**Comment by maxiride** [comment]
> Also running into this, has anyone sorted it out?

I've simply added a `.releaserc.json` file as if it was a nodejs project with the following settings (of course they should be adapted to the project use case):


```json
{
  "branches": [
    "+([0-9])?(.{+([0-9]),x}).x",
    "main",
    {
      "name": "beta",
      "prerelease": true
    }
  ],
  "plugins": [
    "@semantic-release/commit-analyzer",
    "@semantic-release/release-notes-generator",
    "@semantic-release/github"
  ]
}
```

I then invoke the action as usual in a github workflow:

```yml
      - name: Execute Semantic Release
        id: semantic
        uses: cycjimmy/semantic-release-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```
