### ISSUE TITLE
Tag push not triggering workflows which are configured to run on tag push, even with PAT configured

### ISSUE THREAD

**Issue by ryan-jan** [cycjimmy/semantic-release-action#128]
**Describe the bug**
I have a workflow set to trigger on pushed tags, however when this semantic-release action creates a tag my other action is not triggered. I have set the GITHUB_TOKEN to use a PAT but it still seems to create the tag using the semantic-release bot, is this what is causing the issue. The release itself is created as me (because of the PAT) but the tag is not.

**Expected behavior**
When using a PAT in the GITHUB_TOKEN variable the tag would be created and pushed using the PAT.

**Comment by antonmihaylov** [comment]
I have the same problem, are there any known workarounds for this?

**Comment by benkeil** [comment]
I only get it to work when I use my PAT in the `actions/checkout@v4` and the `cycjimmy/semantic-release-action@v4` actions.

ci.yaml

```yaml
name: ci

on:
  push:
    branches: [ main ]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_TOKEN }}
      - uses: actions/setup-node@v4
        with:
          node-version: "lts/*"
      - uses: cycjimmy/semantic-release-action@v4
        name: semantic release
        id: semantic
        env:
          GITHUB_TOKEN: "${{ secrets.GH_TOKEN }}"
      - name: write job summary
        run: |
          echo "__release-version__: ${{ steps.semantic.outputs.new_release_version }}" >> $GITHUB_STEP_SUMMARY
          echo "__release-tag__: ${{ steps.semantic.outputs.new_release_git_tag }}" >> $GITHUB_STEP_SUMMARY
```

```yaml
name: publish

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

run-name: ${{ github.ref_name }}

permissions:
  contents: read
  packages: write
  id-token: write

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
```
