### ISSUE TITLE
Authentication

### ISSUE THREAD

**Issue by denispeyrusaubes** [cycjimmy/semantic-release-action#133]
**Describe the bug**

```
An error occurred while running semantic-release: Error: Could not add chart repository. Wrong credentials?
...
Error: looks like "http://myurl/" is not a valid chart repository or cannot be reached: failed to fetch http://myurl : 401 Unauthorized
```

This message appears when running `cycjimmy/semantic-release-action@v3

**Workflow**

```
      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v3
        with:
          branch: "*"   
          extra_plugins: |
            semantic-release-helm3 
        env:
          GITHUB_TOKEN: ${{ secrets.RTG_CI_TOKEN }}
          HELM_REPO_USERNAME: YYYYYY
          HELM_REPO_PASSWORD: XXXXXX
```
**Expected behavior**

Action runs following command : 
```
helm repo add semantic-release-helm http://mychartmuseum.domain.io:9999/
```

Authentication information are not used by helm as it should :
 ```
       env:
          HELM_REPO_USERNAME: YYYYYY
          HELM_REPO_PASSWORD: XXXXXX
```

**Additional context**

 can add repo and push charts to this repo using command line (but using authentication parameters)

Any idea ?
