### ISSUE TITLE
Action fails to set a release in GitHub

### ISSUE THREAD

**Issue by tal-rofe** [cycjimmy/semantic-release-action#136]
**Describe the bug**
I use this action to release and tagging my repository.
However, it fails on the release GitHub phase:
```
[7:32:52 AM] [semantic-release] › ✖  An error occurred while running semantic-release: RequestError [HttpError]: Not Found
    at /home/runner/work/_actions/cycjimmy/semantic-release-action/v2/node_modules/@octokit/request/dist-node/index.js:88:21
Error: HttpError: Not Found
    at processTicksAndRejections (internal/process/task_queues.js:97:5) {
  status: 404,
  response: {
    url: 'https://api.github.com/repos/Exlint/node-environment/releases',
    status: 404,
    headers: {
      'access-control-allow-origin': '*',
      'access-control-expose-headers': 'ETag, Link, Location, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Used, X-RateLimit-Resource, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval, X-GitHub-Media-Type, X-GitHub-SSO, X-GitHub-Request-Id, Deprecation, Sunset',
      connection: 'close',
      'content-encoding': 'gzip',
      'content-security-policy': "default-src 'none'",
      'content-type': 'application/json; charset=utf-8',
      date: 'Sun, 30 Oct 2022 07:32:52 GMT',
      'referrer-policy': 'origin-when-cross-origin, strict-origin-when-cross-origin',
      server: 'GitHub.com',
      'strict-transport-security': 'max-age=31536000; includeSubdomains; preload',
      'transfer-encoding': 'chunked',
      vary: 'Accept-Encoding, Accept, X-Requested-With',
      'x-accepted-oauth-scopes': 'repo',
      'x-content-type-options': 'nosniff',
      'x-frame-options': 'deny',
      'x-github-media-type': 'github.v3; format=json',
      'x-github-request-id': '0500:725E:67B1BD7:D608A21:635E28A4',
      'x-oauth-scopes': 'repo',
      'x-ratelimit-limit': '5000',
      'x-ratelimit-remaining': '4992',
      'x-ratelimit-reset': '1667117391',
      'x-ratelimit-resource': 'core',
      'x-ratelimit-used': '8',
      'x-xss-protection': '0'
    },
    data: {
      message: 'Not Found',
      documentation_url: 'https://docs.github.com/rest/reference/repos#create-a-release'
    }
  },
  request: {
    method: 'POST',
    url: 'https://api.github.com/repos/Exlint/node-environment/releases',
    headers: {
      accept: 'application/vnd.github.v3+json',
      'user-agent': 'octokit-rest.js/19.0.5 octokit-core.js/4.1.0 Node.js/12.22.7 (linux; x64)',
      authorization: 'token [REDACTED]',
      'content-type': 'application/json; charset=utf-8'
    },
    body: '{"tag_name":"v1.0.1","target_commitish":"main","name":"v1.0.1","body":"## [1.0.1](https://github.com/Exlint/node-environment/compare/v1.0.0...v1.0.1) (2022-10-30)\\n\\n\\n### Bug Fixes\\n\\n* 🐞 set pnpm version ([1c949f5](https://github.com/Exlint/node-environment/commit/1c949f575ba32b551a50672075f95e9ed84a103c))\\n\\n\\n\\n","prerelease":false}',
    request: { agent: undefined, hook: [Function: bound bound register] }
  },
  attemptNumber: 4,
  retriesLeft: 0,
  pluginName: '@semantic-release/github'
}
```

**Workflow**
```yaml
name: Semantic Release

on:
    push:
        branches: [main]

jobs:
    release:
        name: Release version
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Semantic Release
              uses: cycjimmy/semantic-release-action@v2
              with:
                  extra_plugins: |
                      @semantic-release/changelog
                      @semantic-release/commit-analyzer
                      @semantic-release/git
                      @semantic-release/npm
              env:
                  GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
```

**Expected behavior**
I expect the action to create a release but it fails

**Additional context**
I provided access token for the action with following permissions:
<img width="501" alt="image" src="https://user-images.githubusercontent.com/100444463/198867801-c090c7b0-f14d-4952-b0c3-afd5e91c0316.png">
