### ISSUE TITLE
@semantic-release/git@8.0.0 requires a peer of semantic-release@>=16.0.0-beta <17.0.0 but none is installed.

### ISSUE THREAD

**Issue by bennypowers** [cycjimmy/semantic-release-action#14]
**Describe the bug**
```
##[error]npm WARN @semantic-release/git@8.0.0 requires a peer of semantic-release@>=16.0.0-beta <17.0.0 but none is installed. You must install peer dependencies yourself.
```

**Workflow**
https://github.com/bennypowers/stripe-elements/blob/18a1bdc61abb33700fb6cda37bbc2ac85f3dc998/.github/workflows/release.yml#L42-L62

**Expected behavior**
semantic release runs to completion

**Additional context**
This issue popped up recently.
- [successful run from 2 days ago](https://github.com/bennypowers/stripe-elements/runs/379845392)
- [failing run from today](https://github.com/bennypowers/stripe-elements/runs/383252423)

**Comment by favoyang** [comment]
Because you will install the latest version of extra_plugins in the github action. While the semantic-release-action haven't update to 16.0.0 yet.

Workaround: limit the extra_plugins to old version.

```
    - name: Release
      uses: cycjimmy/semantic-release-action@v2
      with:
        extra_plugins: |
          @semantic-release/changelog@3.0.0
          @semantic-release/git@7.0.18
        branch: master
```

**Comment by cycjimmy** [comment]
It is recommended to manually specify a version of semantic-release and its plugins to prevent errors caused during the official semantic-release upgrade.

```yaml
- name: Semantic Release
  uses: cycjimmy/semantic-release-action@v2
  with:
    semantic_version: 15.14.0
    extra_plugins: |
      @semantic-release/git@7.0.18
  env:
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
```

And a new feature will be released soon later to use the latest version of semantic-release by default.
