### ISSUE TITLE
[TODAY] Github Actions - Genera an error

### ISSUE THREAD

**Issue by okarook** [cycjimmy/semantic-release-action#143]
**Describe the bug**
My Github action has an error
This error occurred today, yesterday everything was fine

![](https://user-images.githubusercontent.com/4731245/211103021-0c0c0280-9770-41c2-88a3-d56e13479309.png)

**Workflow**
This is my action

```
name: Semantic Release
on:
  push:
    branches: [ production ]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16.17.0

      - name: Install Dependencies
        run: yarn install

      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v2
        id: semantic  
        with:
          branch: production
        env:
          GITHUB_TOKEN: ${{ secrets.XXXX }}
  
```

**Expected behavior**
This action should work in my GitHub

**Additional context**
I have seen that the [semantic-release](https://github.com/semantic-release/semantic-release) package a few minutes ago updated to a new version.
