### ISSUE TITLE
README: Latest semantic-version release not used by default in v3

### ISSUE THREAD

**Issue by MikeMcC399** [cycjimmy/semantic-release-action#148]
- This issue follows on from the discussion in issue https://github.com/cycjimmy/semantic-release-action/issues/143.

## Problem description

The [README](https://github.com/cycjimmy/semantic-release-action/blob/main/README.md#semantic_version) statement "If no version range is specified, latest version will be used by default." is not correct for `cycjimmy/semantic-release-action@v3`.

### Current README text

The [README section: Semantic version](https://github.com/cycjimmy/semantic-release-action/blob/main/README.md#semantic_version) contains the section:

"**semantic_version**

{Optional Input Parameter} Specify specifying version range for semantic-release.<br>If no version range is specified, latest version will be used by default."

```yaml
steps:
  - name: Checkout
    uses: actions/checkout@v3
  - name: Semantic Release
    uses: cycjimmy/semantic-release-action@v3
    with:
      semantic_version: 15.13.28  # It is recommended to specify specifying version range
                                  # for semantic-release.
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
```

*It is recommended to manually specify a version of semantic-release to prevent errors caused during the official semantic-release upgrade.*"

## Steps to reproduce

Run using the following from [README section: Basic Usage](https://github.com/cycjimmy/semantic-release-action/blob/main/README.md#basic-usage)

```yaml
steps:
  - name: Checkout
    uses: actions/checkout@v3
  - name: Semantic Release
    uses: cycjimmy/semantic-release-action@v3
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
```

and examine the GitHub action log files which show:

```text
[semantic-release] › ℹ  Running semantic-release version 19.0.5
```
[semantic-release version 19.0.5](https://github.com/semantic-release/semantic-release/releases/tag/v19.0.5) is not the latest release of [semantic-release](https://github.com/semantic-release/semantic-release/).

The repository [semantic-release](https://github.com/semantic-release/semantic-release/releases) currently shows [v20.1.0](https://github.com/semantic-release/semantic-release/releases/tag/v20.1.0) tagged as "Latest".

## Expected behavior

The [README](https://github.com/cycjimmy/semantic-release-action/blob/main/README.md#semantic_version) file should correctly reflect how `cycjimmy/semantic-release-action@v3` works.

## Suggested fix

In the [README](https://github.com/cycjimmy/semantic-release-action/blob/main/README.md#semantic_version) file change:

"If no version range is specified, latest version will be used by default."

to

"If no version range is specified with `cycjimmy/semantic-release-action@v3` then [semantic-release](https://github.com/semantic-release/semantic-release/) version [19.0.5](https://github.com/semantic-release/semantic-release/releases/tag/v19.0.5) is used. Earlier versions of `cycjimmy/semantic-release-action` default to using the latest version of [semantic-release](https://github.com/semantic-release/semantic-release/), so in this case you should specify version 19 or lower.

*Note: [Version 20.0.0](https://github.com/semantic-release/semantic-release/releases/tag/v20.0.0) of [semantic-release](https://github.com/semantic-release/semantic-release/) and later is currently incompatible with any GitHub JavaScript action, including `cycjimmy/semantic-release-action`, since it requires Node.js 18. GitHub currently only offers `node12` and `node16` environments (see [`runs` for JavaScript actions](https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions#runs-for-javascript-actions)).*

In several places the English sounds a bit strange with "Specify specifying version range ...". That would be better as simply "Specify version range ...".

It would also be advisable to update the example.
