### ISSUE TITLE
Can not specify a release branch

### ISSUE THREAD

**Issue by tjoskar** [cycjimmy/semantic-release-action#15]
**Describe the bug**
It does not work to specify a release branch

**Workflow**
```
- name: 📦 Semantic Release
  uses: cycjimmy/semantic-release-action@v2
  id: semantic
  with:
    branch: develop
  env:
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

**Expected behavior**
I expect the release to be done on the `develop` branch but instead, I get this message:

> This test run was triggered on the branch develop, while semantic-release is configured to only publish from master, therefore a new version won’t be published.

**Additional context**
If you take a look at the [semantic API](https://github.com/semantic-release/semantic-release/blob/master/docs/developer-guide/js-api.md), you can see it accept `branches` but this code pass in `branch`:
https://github.com/cycjimmy/semantic-release-action/blob/221f1449e1a6be81d43b7e0067b7ff312bbd67fc/src/handleOptions.js#L13

I can create a PR if you want.
