### ISSUE TITLE
Does not support semantic-release version 20

### ISSUE THREAD

**Issue by Nicklason** [cycjimmy/semantic-release-action#155]
**Describe the bug**
When using semantic-release version 20 the job crashes because semantic-release now exports package as ESM instead of CommonJS.

**Workflow**

```yaml
steps:
  - name: Checkout
    uses: actions/checkout@v3
  - name: Semantic Release
    uses: cycjimmy/semantic-release-action@v3
    with:
      semantic_version: 20
```

**Expected behavior**
This action should work properly with the newest version of semantic-release.

**Additional context**
Release notes https://github.com/semantic-release/semantic-release/releases/tag/v20.0.0

**Comment by elmarti** [comment]
For anyone else seeing this problem, for now I have fixed semantic release to 19, which at least gets my builds to pass: 
```
      - name: Semantic Release
        id: semantic
        uses: cycjimmy/semantic-release-action@v2
        with:
          semantic_version: 19
```
