### ISSUE TITLE
Release action fails with non-specific error

### ISSUE THREAD

**Issue by kdmcguire** [cycjimmy/semantic-release-action#157]
**Describe the bug**

Our release action is failing, meaning no release is created. The error message is:

`Error: Command failed: npm install @semantic-release/commit-analyzer @semantic-release/release-notes-generator @semantic-release/npm @semantic-release/github @semantic-release/git --silent`

It stopped working yesterday.

**Workflow**

```
name: Release
on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  release:
    name: release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Setup Node.js with GitHub Package Registry
        uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: "https://npm.pkg.github.com"
          scope: "britishredcrosssociety"

      - name: Install
        run: npm ci

      - name: Build
        run: npm run build:package

      - name: Semantic Release
        id: semantic
        uses: cycjimmy/semantic-release-action@v3
        with:
          semantic_version: 19.0.5
          extra_plugins: |
            @semantic-release/commit-analyzer
            @semantic-release/release-notes-generator
            @semantic-release/npm
            @semantic-release/github
            @semantic-release/git
        env:
          GITHUB_TOKEN: ${{ secrets.BRCAUTOBOT_TOKEN }}
          NPM_TOKEN: ${{ secrets.BRCAUTOBOT_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.BRCAUTOBOT_TOKEN }}
```

**Expected behavior**
The release action should continue, write the version number change and release notes, and publish a release and github packages package.

**Additional context**

The change that the release action first failed for was upgrading the prettier package from 2.8.4 to 2.8.6. This should be unrelated, right?

Related installed packages:

- "semantic-release": "19.0.5",
- "@semantic-release/changelog": "6.0.2",
- "@semantic-release/commit-analyzer": "9.0.2",
- "@semantic-release/git": "10.0.1",
- "@semantic-release/github": "8.0.7",
- "@semantic-release/npm": "9.0.2",
