### ISSUE TITLE
Error: Error: Command failed: npm install

### ISSUE THREAD

**Issue by tal-rofe** [cycjimmy/semantic-release-action#159]
I have the following workflow config:
```yaml
name: Semantic Release

on:
    push:
        branches: [main]

jobs:
    release:
        name: Release version
        permissions:
            contents: write

        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3
              with:
                token: ${{ secrets.SEMANTIC_RELEASE_GH_TOKEN }}

            - name: Semantic Release
              uses: cycjimmy/semantic-release-action@v3
              with:
                  extra_plugins: |
                      @semantic-release/changelog
                      @semantic-release/commit-analyzer
                      @semantic-release/git
                      @semantic-release/npm
              env:
                  GITHUB_TOKEN: ${{ secrets.SEMANTIC_RELEASE_GH_TOKEN }}
```

But it fails:

```
Run cycjimmy/semantic-release-action@v3
  with:
    extra_plugins: @semantic-release/changelog
  @semantic-release/commit-analyzer
  @semantic-release/git
  @semantic-release/npm
  
  env:
    GITHUB_TOKEN: ***

added 317 packages, and audited 518 packages in 6s

44 packages are looking for funding
  run `npm fund` for details

1 high severity vulnerability

To address all issues, run:
  npm audit fix

Run `npm audit` for details.

Error: Error: Command failed: npm install @semantic-release/changelog @semantic-release/commit-analyzer @semantic-release/git @semantic-release/npm --silent
```
