### ISSUE TITLE
Incompatibility with semantic-release >v20

### ISSUE THREAD

**Issue by carlobernardini** [cycjimmy/semantic-release-action#168]
**Describe the bug**
Semantic release only supports esm [as of v20](https://github.com/semantic-release/semantic-release/releases/tag/v20.0.0). This action, however, still imports semantic-release [using cjs](https://github.com/cycjimmy/semantic-release-action/blob/main/src/index.js#L29). As a consequence, it cannot use the latest major versions that are esm-only.

**Workflow**
For example:
```
   - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v3
        with:
          semantic_version: 21
          extra_plugins: semantic-release-slack-bot@4.0.2
        env:
          SLACK_WEBHOOK: ***
          GH_TOKEN: ***
          NPM_TOKEN: ***
```

**Additional context**
The resulting error in the CI output:
```
Error: Error [ERR_REQUIRE_ESM]: require() of ES Module /home/runner/work/_actions/cycjimmy/semantic-release-action/v3/node_modules/semantic-release/index.js from /home/runner/work/_actions/cycjimmy/semantic-release-action/v3/src/index.js not supported.
Instead change the require of /home/runner/work/_actions/cycjimmy/semantic-release-action/v3/node_modules/semantic-release/index.js in /home/runner/work/_actions/cycjimmy/semantic-release-action/v3/src/index.js to a dynamic import() which is available in all CommonJS modules.
```
