### ISSUE TITLE
Not Writing CHANGELOG.md

### ISSUE THREAD

**Issue by bennypowers** [cycjimmy/semantic-release-action#17]
**Describe the bug**
While running `Release`, I don't get changelog updates

**Workflow**
```yml
name: Release
on:
  push:
    branches:
      - master

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: Install dependencies
        run: npm ci
      - name: Install Coverage Reporter
        run: |
          curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
          chmod +x ./cc-test-reporter
          ./cc-test-reporter before-build
      - name: Run Tests
        run: npm test
      - name: Format Coverage
        run: ./cc-test-reporter format-coverage -t lcov -o coverage/coverage.json coverage/lcov.info
      - name: Upload Coverage
        uses: actions/upload-artifact@v1
        with:
          name: coverage
          path: coverage
      - name: Cache dependencies
        uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

  release:
    name: Release
    needs: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Install dependencies
        run: npm ci
      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v2
        id: semantic   # Need an `id` for output variables
        with:
          branch: master
          extra_plugins: |
            @semantic-release/git
            @semantic-release/changelog
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

  upload-coverage:
    name: Upload Coverage
    runs-on: ubuntu-latest
    needs:
      - Test
      - Release
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: Download coverage
        uses: actions/download-artifact@v1
        with:
          name: coverage
      - name: Install Coverage Reporter
        run: |
          curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
          chmod +x ./cc-test-reporter
      - name: Upload Coverage
        run: ./cc-test-reporter upload-coverage -i coverage/coverage.json
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}

  docs-deploy:
    runs-on: ubuntu-latest
    needs: Release
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: Install dependencies
        run: npm ci
      - name: Build docs
        run: npm run storybook:build
      - name: Deploy docs
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          ACCESS_TOKEN: ${{ secrets.GH_TOKEN }}
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: storybook-static # The folder the action should deploy.
```

**Expected behavior**
I expect changelog to be updated

**Additional context**
package.json:
```json
{
  "name": "@power-elements/stripe-elements",
  "version": "2.0.1",
  "description": "Web Component wrapper for stripe elements",
  "main": "index.js",
  "module": "index.js",
  "directories": {
    "test": "test"
  },
  "scripts": {
    "postinstall": "patch-package",
    "prepare": "npm run build",
    "build": "run-s build:**",
    "build:rollup": "rollup -c",
    "build:types": "tsc && sh scripts/finish-declarations.sh",
    "build:analyze:json": "wca analyze src/*.js --outFile custom-elements.json",
    "build:analyze:markdown": "cp src/README.template.md README.md && wca analyze src/*.js --silent --markdown.headerLevel 3 >> README.md",
    "test": "karma start --coverage",
    "test:watch": "karma start --auto-watch=true --single-run=false --reporters mocha,osx",
    "test:update-snapshots": "karma start --update-snapshots",
    "test:prune-snapshots": "karma start --prune-snapshots",
    "site:build": "npm run storybook:build",
    "storybook": "start-storybook --docs --node-resolve --watch --open --babel",
    "storybook:build": "mv .babelrc bak && build-storybook && mv bak .babelrc",
    "watch": "rollup -cw"
  },
  "repository": {
    "type": "git",
    "url": "https://github.com/bennypowers/stripe-elements.git"
  },
  "files": [
    "*.d.ts",
    "*.js",
    "*.js.map",
    "custom-elements.json",
    "CHANGELOG.md",
    "README.md",
    "src/*"
  ],
  "types": "index.d.ts",
  "keywords": [
    "web-components",
    "lit-element",
    "lit-element-2.0",
    "stripe",
    "payment",
    "payment-request",
    "payment request api"
  ],
  "author": "Benny Powers <web@bennypowers.com>",
  "license": "ISC",
  "bugs": {
    "url": "https://github.com/bennypowers/stripe-elements/issues"
  },
  "homepage": "https://bennypowers.dev/stripe-elements",
  "husky": {
    "hooks": {
      "pre-commit": "npm run build:analyze:markdown && npm run build:analyze:json && git add README.md && git add custom-elements.json"
    }
  },
  "release": {
    "branches": [
      "master"
    ],
    "plugins": [
      "@semantic-release/commit-analyzer",
      "@semantic-release/github",
      "@semantic-release/npm",
      "@semantic-release/release-notes-generator",
      "@semantic-release/git",
      "@semantic-release/changelog"
    ]
  },
  "devDependencies": {
    "@apollo-elements/eslint-config": "^1.1.1",
    "@babel/core": "^7.8.0",
    "@babel/plugin-proposal-class-properties": "^7.8.0",
    "@babel/plugin-proposal-decorators": "^7.8.0",
    "@babel/plugin-proposal-dynamic-import": "^7.8.0",
    "@babel/plugin-proposal-optional-chaining": "^7.8.3",
    "@babel/plugin-syntax-dynamic-import": "^7.8.0",
    "@babel/plugin-transform-runtime": "^7.8.3",
    "@babel/preset-env": "^7.8.2",
    "@material/mwc-button": "^0.12.0",
    "@material/mwc-textfield": "^0.12.0",
    "@open-wc/demoing-storybook": "^1.8.5",
    "@open-wc/testing": "^2.5.1",
    "@open-wc/testing-karma": "^3.2.30",
    "@power-elements/codesandbox-button": "0.0.2",
    "@power-elements/json-viewer": "^1.0.1",
    "@rollup/plugin-commonjs": "^11.0.1",
    "@rollup/plugin-node-resolve": "^7.0.0",
    "@types/karma": "^3.0.5",
    "babel-eslint": "^10.0.3",
    "bound-decorator": "^1.1.0",
    "chai-things": "^0.2.0",
    "credit-card-type": "^8.3.0",
    "crocks": "^0.12.4",
    "deepmerge": "^4.2.2",
    "eslint": "^6.8.0",
    "eslint-config-google": "^0.14.0",
    "eslint-plugin-html": "^6.0.0",
    "eslint-plugin-json": "^2.0.1",
    "eslint-plugin-no-loops": "^0.3.0",
    "eslint-plugin-no-only-tests": "^2.4.0",
    "husky": "^4.2.1",
    "karma-helpful-reporter": "^0.3.4",
    "karma-osx-reporter": "^0.2.1",
    "karma-tap-reporter": "0.0.6",
    "karma-tape-reporter": "^1.0.3",
    "luhn-js": "^1.1.2",
    "npm-run-all": "^4.1.5",
    "patch-package": "^6.2.0",
    "rollup": "^1.29.1",
    "rollup-plugin-babel": "^4.3.3",
    "rollup-plugin-lit-css": "^2.0.0",
    "sinon": "^8.1.1",
    "sinon-chai": "^3.4.0",
    "stylelint-config-standard": "^19.0.0",
    "typescript": "^3.7.4",
    "web-component-analyzer": "^1.0.1"
  },
  "dependencies": {
    "@babel/runtime": "^7.8.3",
    "@lavadrop/camel-case": "^0.4.0",
    "@lavadrop/kebab-case": "^3.0.0",
    "@lavadrop/pick": "^0.8.0",
    "@morbidick/lit-element-notify": "^1.0.2",
    "@open-wc/lit-helpers": "^0.2.6",
    "@pacote/memoize": "^1.1.1",
    "@typed/curry": "^1.0.1",
    "@types/stripe-v3": "^3.1.14",
    "lit-element": "^2.2.1"
  }
}
```
