### ISSUE TITLE
override plugin version

### ISSUE THREAD

**Issue by vytautas-pranskunas-** [cycjimmy/semantic-release-action#172]
There was an error introduced here: https://github.com/semantic-release/commit-analyzer/issues/517
And i need to override version

"@semantic-release/commit-analyzer@9.0.2", 
            "conventional-changelog-conventionalcommits@6.1.0"

How can i do this?

This i snot valid
 - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v3
        id: semantic
        with:
          semantic_version: 19
          plugins: [
            "@semantic-release/commit-analyzer@9.0.2", 
            "conventional-changelog-conventionalcommits@6.1.0"
            ]
          extra_plugins: |
            @semantic-release/git
            @semantic-release/changelog
            @semantic-release/release-notes-generator@10.0.3
            conventional-changelog-eslint
        env:
          RUNNER_DEBUG: 1

also when adding those plugins to extra_plugins those versions has no effect.
Any ideas?

**Comment by dnaprawa** [comment]
I've got the same problem

**Comment by BrendanGalloway** [comment]
The action does not have a 'plugins' input - putting the versions and their pins in extra_plugins works for us

```yaml
      - uses: cycjimmy/semantic-release-action@v4
        id: semantic
        with:
          extra_plugins: |
            conventional-changelog-conventionalcommits@6.1.0
            @semantic-release/commit-analyzer@10.0.1
```
