### ISSUE TITLE
How to make outputs variables affct following setps ?

### ISSUE THREAD

**Issue by RedmondLee** [cycjimmy/semantic-release-action#22]
Hi there,
Love for your distinguished work , please excuse me for the quesion.
I 'm wondering how to make outputs variables affct following setps ,since I 'd like to make it automatically modify version number while my workflow publish my library to Pypi.
Your "Using Output Variables" example didn't make me understand how to pass variables into those "run" parts codes.
Thanks a lot.

**Comment by RedmondLee** [comment]
I wrote my code this way ,but 'steps.semantic.outputs.new_release_version' does not work.
```
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel twine jinja2
    - name: Scan release version
      uses: cycjimmy/semantic-release-action@v2
      id: semantic 
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Replace release version
      run:
        python replaceVer.py steps.semantic.outputs.new_release_version
```
