### ISSUE TITLE
Can't get this action to work

### ISSUE THREAD

**Issue by peterfortuin** [cycjimmy/semantic-release-action#222]
**Describe the bug**
I want to use this action, but it looks like it's installing the tool with npm, but nothing more. 

I get the following logging:

Run cycjimmy/semantic-release-action@v3.4.1
  
```
added 317 packages, and audited 518 packages in 5s
(node:2350) ExperimentalWarning: CommonJS module /opt/hostedtoolcache/node/23.2.0/x64/lib/node_modules/npm/node_modules/debug/src/node.js is loading ES Module /opt/hostedtoolcache/node/23.2.0/x64/lib/node_modules/npm/node_modules/supports-color/index.js using require().
Support for loading ES Module in require() is an experimental feature and might change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
44 packages are looking for funding
  run `npm fund` for details
[9](https://github.com/user/repository/actions/runs/11851724735/job/33028685665#step:7:10) vulnerabilities (2 moderate, 7 high)
To address issues that do not require attention, run:
  npm audit fix
To address all issues (including breaking changes), run:
  npm audit fix --force
Run `npm audit` for details.
```

**Workflow**
I have added a .releaserc file and added the following to my pipeline configuration:
```
- name: Semantic Release
  id: semantic
  uses: cycjimmy/semantic-release-action@v3.4.1
  with:
    tag_format: ${{ inputs.service-name }}-v${version}
    working_directory: ./${{ inputs.service-name }}
  env:
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

**Expected behavior**
Semantic release tool is started and I should see an error or success.

**Additional context**
I run the semantic-release tool in a subdirectory of my repository.
