### ISSUE TITLE
Action is ignoring (default) branches

### ISSUE THREAD

**Issue by jakobrosenberg** [cycjimmy/semantic-release-action#24]
**Describe the bug**
If I run the action on an alpha branch I get the following error
``` 
"while semantic-release is configured to only publish from master, therefore a new version won’t be published."
```

It doesn't make any difference whether I use the default branches or specify them manually in ``package.json``.

**Comment by cycjimmy** [comment]
The action runs by default on the `master` branch. You can set the `branch` property to change its default behavior.

```yaml
- name: Semantic Release
  uses: cycjimmy/semantic-release-action@v2
  with:
     branch: alpha     # set branch property to alpha
  env:
     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
     NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
```

**Comment by jakobrosenberg** [comment]
@cycjimmy thank you for the quick reply. Are there any plans to support the branches feature of semantic-release v16 ?

**Comment by cycjimmy** [comment]
Of course, the feature for branches looks good. I will support it as possible after my work.

**Comment by jakobrosenberg** [comment]
Amazing! Thank you.

**Comment by cycjimmy** [comment]
Thanks for your issue. And now semantic-release-action@v2.3.0 supports branches. @jakobrosenberg

**Comment by jakobrosenberg** [comment]
Thanks for your efforts @cycjimmy . I just tried the update, but I'm still getting the error from before.

This is my Github action:

```yaml
# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  ['push']

jobs:
  publish:

    runs-on: ubuntu-latest
  
    steps:
    - uses: actions/checkout@v2
    - uses: cycjimmy/semantic-release-action@v2.3.0
    
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
    - run: |
        echo $RELEASE_VERSION
        echo $RELEASE_MAJOR
        echo $RELEASE_MINOR
        echo $RELEASE_PATCH
```
