### ISSUE TITLE
[Feature] Add PR for Main

### ISSUE THREAD

**Issue by DutraGames** [cycjimmy/semantic-release-action#241]
**Is your feature request related to a problem? Please describe.**  
As far as I've seen, there isn't a specific problem related to this.

**Describe the solution you'd like**  
When closing a pull request to `main`, before committing directly to the `main` branch (where it's executed), it could create a temporary branch and open a PR to `main` just for that change, while ignoring PRs coming from this temporary branch.

**Describe alternatives you've considered**  
I considered using the `Create Pull Request` action by `peter-evans`, but it "successfully failed" — since it would create the temporary branch from `main`, it wouldn't detect any changes between the copy branch and `main`.

**Additional context**  
Since my `main` branch is protected by repository rules, I need to generate this release via a PR.

**Workflow**:
```yaml
name: Release

on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Release
        uses: cycjimmy/semantic-release-action@v4
        with:
          semantic_version: 24.2.3
          extra_plugins: |
            @semantic-release/changelog@6.0.3
            @semantic-release/git@10.0.1
            conventional-changelog-conventionalcommits@8.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.SEMATIC }}
```

**.releaserc**:
```json
{
  "branches": [
    "main"
  ],
  "ci": false,
  "plugins": [
    [
      "@semantic-release/commit-analyzer",
      {
        "preset": "conventionalcommits"
      }
    ],
    [
      "@semantic-release/release-notes-generator",
      {
        "preset": "conventionalcommits"
      }
    ],
    [
      "@semantic-release/github",
      {
        "successComment": "This ${issue.pull_request ? 'PR is included' : 'issue has been resolved'} in version ${nextRelease.version} :tada:",
        "labels": false,
        "releasedLabels": false
      }
    ],
    [
      "@semantic-release/changelog",
      {
        "changelogFile": "CHANGELOG.md",
        "changelogTitle": "# Changelog\n\nAll notable changes to this project will be documented in this file."
      }
    ],
    [
      "@semantic-release/git",
      {
        "assets": [
          "CHANGELOG.md"
        ],
        "message": "chore(release): version ${nextRelease.version} [skip ci]\n\n${nextRelease.notes}"
      }
    ]
  ]
}
```
