### ISSUE TITLE
Support releasing with node 22

### ISSUE THREAD

**Issue by DarkAtra** [cycjimmy/semantic-release-action#247]
@cycjimmy i'm running into the same [issue that was described here](https://github.com/cycjimmy/semantic-release-action/issues/96) - just for node 22. The project explicitly asks for node 22 in it's `package.json`:
```json
"engines": {
  "node": ">=22"
}
```
and we also setup node 22 in our action like so:
```yaml
- name: Set up Node 22
  uses: actions/setup-node@v4.1.0
  with:
    node-version: 22
```
but the release fails with:
```
The engine "node" is incompatible with this module. Expected version ">=22". Got "20.18.0"
```
likely because the semantic release action [runs using node 20](https://github.com/cycjimmy/semantic-release-action/blob/b2ec2708bf20a96621f9926d1e4c73c7b57a89f9/action.yml#L64).

Would it be possible to update to node 22 or maybe somehow use the node version from the environment?
