### ISSUE TITLE
How to specify specific version of semantic release plugins?

### ISSUE THREAD

**Issue by kumarharsh** [cycjimmy/semantic-release-action#3]
**Is your feature request related to a problem? Please describe.**
There are times when semantic-release breaks or updates it's API between major releases. I want to reliably set up semantic release workflow using this action. For doing it, I'd like to be able to specify the versions of semantic-release and it's `@semantic-release/*` plugins. This is already done in `package.json`, but how do I ensure my workflow picks it up?

**Describe the solution you'd like**
A way to specify version for semantic release or it's plugins.

**Describe alternatives you've considered**
-

**Comment by cycjimmy** [comment]
`semantic-release-action` uses the latest stable version of `semantic-release`, temporarily unable to specify the version. Which version of `semantic-release` you are using? I consider adding this feature if necessary.

The version of extra plugins can be added to the `extra_plugins` configuration.
```yaml
- name: Semantic Release
  uses: cycjimmy/semantic-release-action@v2
  with:
    extra_plugins: |
      @semantic-release/changelog@x.y.z
```
