### ISSUE TITLE
EGITNOPERMISSION Cannot push to the Git repository

### ISSUE THREAD

**Issue by favoyang** [cycjimmy/semantic-release-action#33]
**Describe the bug**

My [GitHub action](https://github.com/openupm/openupm/actions/runs/112680575) returns
```[5:45:09 PM] [semantic-release] › ✔  Run automated release from branch master on repository https://x-access-token:[secure]@github.com/openupm/openupm
[5:45:10 PM] [semantic-release] › ✖  The command "git push --dry-run --no-verify https://x-access-token:[secure]@github.com/openupm/openupm HEAD:master" failed with the error message remote: Permission to openupm/openupm.git denied to github-actions[bot].
fatal: unable to access 'https://github.com/openupm/openupm/': The requested URL returned error: 403.
[5:45:10 PM] [semantic-release] › ℹ  Start step "fail" of plugin "@semantic-release/github"
[5:45:10 PM] [semantic-release] [@semantic-release/github] › ℹ  Verify GitHub authentication
[5:45:11 PM] [semantic-release] [@semantic-release/github] › ℹ  Found existing semantic-release issue #522.
[5:45:12 PM] [semantic-release] [@semantic-release/github] › ℹ  Added comment to issue #522: https://github.com/openupm/openupm/issues/522#issuecomment-632825879.
[5:45:12 PM] [semantic-release] › ✖  EGITNOPERMISSION Cannot push to the Git repository.
[5:45:12 PM] [semantic-release] › ✔  Completed step "fail" of plugin "@semantic-release/github"
semantic-release cannot push the version tag to the branch master on the remote Git repository with URL https://x-access-token:[secure]@github.com/openupm/openupm.

This can be caused by:

    * a misconfiguration of the repositoryUrl (https://github.com/semantic-release/semantic-release/blob/master/docs/usage/configuration.md#repositoryurl) option
    * the repository being unavailable
    * or missing push permission for the user configured via the Git credentials on your CI environment (https://github.com/semantic-release/semantic-release/blob/master/docs/usage/ci-configuration.md#authentication)

##[error]SemanticReleaseError: Cannot push to the Git repository.
```

GitHub Action

```
release:
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/master'
    steps:
    - uses: actions/checkout@v1
    - name: Release
      uses: cycjimmy/semantic-release-action@v2
      with:
        extra_plugins: |
          @semantic-release/changelog
          @semantic-release/git
        branch: master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

**Workflow**
n/a

**Expected behavior**
It should authenticate with GitHub. (```secrets.GITHUB_TOKEN``` is provided by GitHub)

**Additional context**
