### ISSUE TITLE
Re-releasing the same version several times

### ISSUE THREAD

**Issue by Berkmann18** [cycjimmy/semantic-release-action#34]
**Describe the bug**
After releasing several bug fixes, the CI and bot still seem to be releasing the same version (3 times) after it was already released and published.

**Workflow**
If applicable, provide a workflow file to help explain your problem.
```yml
name: Semantic Release

on:
  push:
    branches: [master]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - run: |
          npm ci
          npm run build
      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

```

**Expected behaviour**
Seeing new versions being mentioned in the changelog, commits and tags.

**Additional context**
Cf. https://github.com/Berkmann18/json-fixer

Edit: And why is it not looking at the git tag or `package.json#version` numbers? After doing a manual release, it still re-released the prior version again (https://github.com/Berkmann18/json-fixer/commit/30580b21f99449761e550710cca614e6af75bf87).
