### ISSUE TITLE
MODULE_NOT_FOUND

### ISSUE THREAD

**Issue by gimyboya** [cycjimmy/semantic-release-action#37]
**Describe the bug**
I am getting the following error: `Error: Cannot find module '@semantic-release/changelog'` after adding the changelog plugin to the `.releaserc` file and installing the `@semantic-release/changelog` as a dev dependency in my project.

**Workflow**
```yaml
Release:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    needs: GCR
    if: github.event_name == 'push'
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
```

**Expected behavior**
Since the module is installed, the error shouldn't be.

**Additional context**
The action was working fine until i added the changelog plugin for more clarity here is my configuration:
```json
{
  "branches": ["master", "next"],
  "plugins": ["@semantic-release/commit-analyzer", "@semantic-release/release-notes-generator", "@semantic-release/github", "@semantic-release/changelog"]
}
```
