### ISSUE TITLE
extra_plugins in yaml lead to errors

### ISSUE THREAD

**Issue by frederikhors** [cycjimmy/semantic-release-action#38]
If I use:

```yml
with:
  extra_plugins: |
    @semantic-release/changelog
    @semantic-release/git
```

like you say in Readme, it leads me to https://github.com/cycjimmy/semantic-release-action/issues/34.

If I only use semantic-release config file adding both `@semantic-release/changelog` and `@semantic-release/git` after default plugins everything works.

Am I wrong?
