### ISSUE TITLE
output file

### ISSUE THREAD

**Issue by hssngl** [cycjimmy/semantic-release-action#41]
After running the following workflow I don't get `changelog.md` file in the repository. am I missing something?

```
name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  create:
    branches: [master]

jobs:
  changelog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v2
        with:
          extra_plugins: |
            @semantic-release/changelog
            @semantic-release/git@7
          branch: master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

```
