### ISSUE TITLE
What steps do I need to take for TypeScript packages?

### ISSUE THREAD

**Issue by coaxial** [cycjimmy/semantic-release-action#46]
I'm a bit confused as to where the boundary for this action is.

Considering a TypeScript project, what steps should I run so that this action releases a compiled version of it? Is adding a `npm run build` (where `build` takes care of the TS->JS compilation and outputs the compiled files to `dist/`) step between the `Checkout` and `Semantic Release` steps enough? How do I tell this action to use the contents of `dist/` as the package's contents?

**Comment by cycjimmy** [comment]
It is recommended that to use the `@semantic-release/exec` plugin to build your code. 
And set the `pkgroot` attribute of `@semantic-release/npm` for setting the directory path publishing.

1. Add `@semantic-release/exec` plugin to extra_plugins in your release workflow file.
```yaml
steps:
  ...
  - name: Semantic Release
    uses: cycjimmy/semantic-release-action@v2
    with:
      extra_plugins: |
        @semantic-release/exec
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
```

2. Set semantic release configuration in your repository.
```javascript
module.exports = {
  ...	
  "plugins": [
    ...
    ["@semantic-release/exec", {
      "prepareCmd": "your build code here"
    }],
    ["@semantic-release/npm", {
      "pkgRoot": "dist"
    }]
    ...	
  ]
}
```
