### ISSUE TITLE
Tags are not deleted on release failure

### ISSUE THREAD

**Issue by HeshamMeneisi** [cycjimmy/semantic-release-action#47]
**Describe the bug**
Tags are not cleared on failure

**Workflow**
```yaml
      - name: Checkout
        uses: actions/checkout@v1

      - name: Semantic Release
        id: semantic
        uses: cycjimmy/semantic-release-action@v2
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          extra_plugins: |
            @semantic-release/git
            @semantic-release/exec
            @semantic-release/changelog

       - name: Publish
         run: {some potentially failing code}
```

**Expected behavior**
The release is not created when the publish step fails and the tag is deleted/not created

**Actual Behaviour**
The release is not created but the tag remains there
