### ISSUE TITLE
Error: npm WARN @octokit/plugin-request-log@1.0.2 requires a peer of @octokit/core@>=3 but none is installed. You must install peer dependencies yourself.

### ISSUE THREAD

**Issue by bubkoo** [cycjimmy/semantic-release-action#48]
Error: npm WARN @octokit/plugin-request-log@1.0.2 requires a peer of @octokit/core@>=3 but none is installed. You must install peer dependencies yourself.

**Workflow**

https://github.com/bubkoo/html-to-image/runs/1316761371?check_suite_focus=true

**Expected behavior**

**Additional context**

**Comment by cycjimmy** [comment]
I could see the error information in your project. But this action does not use the dependency of `@octokit/plugin-request-log`. Maybe you use this dependency in other actions, and the NPM installer prompts the error message when this action installing extra plugins.

**Comment by bubkoo** [comment]
The error is in the semantic release action's log. And my workflow is: https://github.com/bubkoo/html-to-image/blob/master/.github/workflows/release.yml

![image](https://user-images.githubusercontent.com/6045824/97382347-2703f100-1906-11eb-956a-223c8266d248.png)

**Comment by cycjimmy** [comment]
Since the working directory of GitHub actions is indistinguishable, this error is due to the NPM check triggered after NPM install. It is determined that the action does not use the dependency in your error. Therefore, it is recommended that you check other actions, or use only this action test to see if there are any same errors reported.

**Comment by paulpach** [comment]
I see the exact same problem:
https://github.com/MirrorNG/MirrorNG/runs/1387550829?check_suite_focus=true#step:10:13

Here is my step:
https://github.com/MirrorNG/MirrorNG/blob/c9fa47f66938e5cc0413ff062c56b0fa985bfe2e/.github/workflows/main.yml#L83

```yaml
      - name: Release
        uses: cycjimmy/semantic-release-action@v2
        id: semantic
        with:
          extra_plugins: |
            @semantic-release/exec
            @semantic-release/changelog
            @semantic-release/git
          branch: master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```
