### ISSUE TITLE
can not publish to GitHub package registry

### ISSUE THREAD

**Issue by bubkoo** [cycjimmy/semantic-release-action#49]
**Describe the bug**

When use config in your repo: https://github.com/cycjimmy/semantic-release-action/blob/master/.github/workflows/release.yml to publish to GitHub package registry

npm ERR! code E404
npm ERR! 404 Not Found - PUT https://registry.npmjs.org/html-to-image - Not found
npm ERR! 404 
npm ERR! 404  'html-to-image@1.3.15' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

**Workflow**

https://github.com/bubkoo/html-to-image/blob/master/.github/workflows/release.yml
https://github.com/bubkoo/html-to-image/runs/1317013266?check_suite_focus=true

**Expected behavior**

**Additional context**

**Comment by cycjimmy** [comment]
GPR only supports the name for scope in `package.json`. 
Please use a name in the format `'@your-github-name/your-package-name'`.

**Comment by bubkoo** [comment]
It works for me with the following config: 

```yaml
      - name: Publish To GitHub Package Registry
        if: steps.semantic.outputs.new_release_published == 'true'
        run: |
          sed -i 's/\("name"\:[[:space:]]*"\)\(html-to-image"\)/\1@bubkoo\/\2/' package.json
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```
