### ISSUE TITLE
Unable to get the changelog/release notes working on the release page

### ISSUE THREAD

**Issue by yrshaikh** [cycjimmy/semantic-release-action#51]
**Describe the bug**
Hi, I am setting up semantic release on my project, I am able to get it working but I have an issue with the changelog/release-notes. It does not show up like how it's supposed to show.

Current behavior -

![image](https://user-images.githubusercontent.com/2232423/104843636-422b3f00-58fe-11eb-9dec-a8e1fd8e72ea.png)

**Workflow**
I have configured the required extra plugins as mentioned in the docs, here is the link to my [workflow file](https://github.com/yrshaikh/good-urls/blob/main/.github/workflows/build_pack_publish_main.yml) on GitHub - 

```
name: Build pack and publish main
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  check_version_number:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Get semantic release version
        uses: cycjimmy/semantic-release-action@v2
        id: semantic_dry
        with:
          branch: main
          dry_run: true
          extra_plugins: |
            @semantic-release/changelog
            @semantic-release/git
            @semantic-release/github
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
    outputs:
      new_release_published: ${{ steps.semantic_dry.outputs.new_release_published }}
      new_release_version: ${{ steps.semantic_dry.outputs.new_release_version }}

  build_package_push:
    needs: check_version_number
    if: needs.check_version_number.outputs.new_release_published == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'
      
      - name:  Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
            dotnet-version: '5.0.x'
      
      - name: Build project
        run: dotnet build --configuration Release -p:Version=${{ needs.check_version_number.outputs.new_release_version }}.0
      
      - name: Package
        run: dotnet pack --configuration Release --output ./artifacts -p:PackageVersion=${{ needs.check_version_number.outputs.new_release_version }}      

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: nuget-artifact
          path: ./artifacts/*.nupkg
          if-no-files-found: error

  tag_version:
    needs: [build_package_push,check_version_number]
    if: needs.check_version_number.outputs.new_release_published == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Get semantic release version
        uses: cycjimmy/semantic-release-action@v2
        id: semantic
        with:
          branch: main
          extra_plugins: |
            @semantic-release/changelog
            @semantic-release/git
            @semantic-release/github
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
      - name: Echo logs
        run: |
          echo ${{ steps.semantic.outputs.new_release_version }}
          echo ${{ steps.semantic.outputs.new_release_major_version }}
          echo ${{ steps.semantic.outputs.new_release_minor_version }}
          echo ${{ steps.semantic.outputs.new_release_patch_version }}
  push_to_nuget:
    needs: [tag_version,check_version_number]
    if: needs.check_version_number.outputs.new_release_published == 'true'
    runs-on: ubuntu-latest
    steps:
    - name: Download artifact
      uses: actions/download-artifact@v2
      with:
        name: nuget-artifact
    - run: ls -R
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.x' # SDK Version to use.
    - name: Upload to nuget
      run: dotnet nuget push ./*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json
```

**Expected behavior**
I want the changelog to be as how most repositories (including this one) shows as highlighted in this screenshot below 

![image](https://user-images.githubusercontent.com/2232423/104843659-57a06900-58fe-11eb-874a-423d22afe5e0.png)

**Additional context**
N/A
