### ISSUE TITLE
How do I get the semantic version number without using dryRun = true

### ISSUE THREAD

**Issue by yrshaikh** [cycjimmy/semantic-release-action#52]
```
  semantic_release_and_nuget_publish:
    needs: [ build ]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Semantic Release
        id: semantic
        uses: cycjimmy/semantic-release-action@v2
        with:
          extra_plugins: |
            @semantic-release/git@7.0.18
            @semantic-release/exec@3.3.8
            @semantic-release/changelog@3.0.0
   
      - name: Nuget build, pack and push..
        run: dotnet build --configuration Release -p:Version=${{ steps.semantic.outputs.new_release_version }}
```

I am not getting any value in `{{ steps.semantic.outputs.new_release_version }}`
