### ISSUE TITLE
Releasing package to Github Package Registry throws 401 Unauthorized

### ISSUE THREAD

**Issue by leovanhaaren** [cycjimmy/semantic-release-action#53]
**Describe the bug**
When using the Github package Registry, a error is thrown `npm notice npm ERR! code E401 npm ERR! 401 Unauthorized - PUT https://npm.pkg.github.com/@organisation/our-repo`

From what I can find out, it must have something to do with the `.npmrc` not being 100% correct. The `RELEASE_TOKEN` token has the correct permissions, as it is the same for both workflows.

**Workflow**
```yaml
name: Release

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
      - next
      - next-major
      - alpha
      - beta

env:
  GITHUB_REPOSITORY: jellow-holding/design-tokens

jobs:
  release:
    name: release
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false # needed so that jellow-holding user gets used for git push

      - name: Setup Node.js with GitHub Package Registry
        uses: actions/setup-node@v1
        with:
          node-version: 14
          registry-url: 'https://npm.pkg.github.com'

      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v2
        id: semantic # Need an `id` for output variables
        with:
          extra_plugins: |
            @semantic-release/git
            @semantic-release/changelog
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }} # PAT is needed because GITHUB_TOKEN is not allowed to push to protected branch
          NPM_TOKEN: ${{ secrets.RELEASE_TOKEN }}
```

**Expected behavior**
A release and package is published to the repository in GItHub

**Additional context**
The workflow below works as a workaround:

```yaml
jobs:
  release:
    name: release
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false # needed so that jellow-holding user gets used for git push

      - name: Setup Node.js with GitHub Package Registry
        uses: actions/setup-node@v1
        with:
          node-version: 14
          registry-url: 'https://npm.pkg.github.com'

      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v2
        id: semantic # Need an `id` for output variables
        with:
          extra_plugins: |
            @semantic-release/git
            @semantic-release/changelog
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }} # PAT is needed because GITHUB_TOKEN is not allowed to push to protected branch

        # publishing is a seperate step as `cycjimmy/semantic-release-action` does not work properly
      - name: Publish package to GitHub Package Registry
        run: npm publish
        if: steps.semantic.outputs.new_release_published == 'true'
        env:
          NODE_AUTH_TOKEN: ${{ secrets.RELEASE_TOKEN }}`
```

```js

module.exports = {
  "dryRun": false,
  "branches": [
    '+([0-9])?(.{+([0-9]),x}).x',
    'main',
    'next',
    'next-major',
    {
      "name": 'beta',
      "prerelease": true
    },
    {
      "name": 'alpha',
      "prerelease": true
    }
  ],
  "plugins": [
    "@semantic-release/commit-analyzer",
    "@semantic-release/release-notes-generator",
    [
      "@semantic-release/changelog",
      {
        "changelogFile": "docs/CHANGELOG.md"
      }
    ],
    ["@semantic-release/npm", {
      "npmPublish": false,
    }],
    "@semantic-release/github",
    [
      "@semantic-release/git",
      {
        "assets": [
          "docs/CHANGELOG.md",
          "package.json",
          "package-lock.json"
        ],
        "message": "chore(release): ${nextRelease.version} [skip ci]\n\n${nextRelease.notes}"
      }
    ]
  ]
};
```

**Comment by vishnu-buildd** [comment]
@agierlicki I am running into the same issues. Could you please help out. I use the following config

```
      - name: release
        run: npx semantic-release
        env:
          GH_TOKEN: ${secrets.GITHUB_TOKEN}
          NODE_AUTH_TOKEN: ${secrets.NPM_TOKEN}
```

NPM_TOKEN is a gh personal token that I generated.
