### ISSUE TITLE
Can't find 'action.yml', 'action.yaml' or 'Dockerfile'

### ISSUE THREAD

**Issue by imgalli** [cycjimmy/semantic-release-action#55]
**Describe the bug**

We're using your semantic release action (thanks!) in a release workflow which has been working fine though we've had a blip where the following error was thrown. One thing to note is that we're using custom runners rather than the standard GH action runners.

```
2021-03-10T11:26:09.3830758Z ##[error]Can't find 'action.yml', 'action.yaml' or 'Dockerfile' under '/tmp/github/_actions/cycjimmy/semantic-release-action/v2'. Did you forget to run actions/checkout before running your local action?
```

**Workflow**

Release, there is a checkout step many steps ahead of the semantic release one.

**Additional context**

As said, we're using a custom runner which could be one key difference. That said the error is quite straightforward sounding yet odd.

Here's an excerpt from our workflow file
```
name: Release
on:
  push:
    branches:
      - master
jobs:
  release:
    name: Release
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        node-version: [14.15.x]
        os:
          - self-hosted-ubuntu-2004

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
        with:
          persist-credentials: false
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm ci
      - name: Release
        uses: cycjimmy/semantic-release-action@v2
        id: semantic
        env:
          GH_TOKEN: ${{ secrets.ACTION_GITHUB_TOKEN }}
```
