### ISSUE TITLE
Unable to authenticate, need: Basic realm="GitHub Package Registry"

### ISSUE THREAD

**Issue by yrshaikh** [cycjimmy/semantic-release-action#78]
**Describe the bug**
Getting this error

![image](https://user-images.githubusercontent.com/2232423/130435251-dccb002e-9725-4da1-a7de-a62c64710ddb.png)

```
Error: Command failed: npm ci --only=prod
npm ERR! code E401
npm ERR! Unable to authenticate, need: Basic realm="GitHub Package Registry"

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-08-23T10_41_00_344Z-debug.log

    at ChildProcess.exithandler (child_process.js:295:12)
    at ChildProcess.emit (events.js:210:5)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5) {
  killed: false,
  code: 1,
  signal: null,
  cmd: 'npm ci --only=prod',
  stdout: '',
  stderr: 'npm ERR! code E401\n' +
    'npm ERR! Unable to authenticate, need: Basic realm="GitHub Package Registry"\n' +
    '\n' +
    'npm ERR! A complete log of this run can be found in:\n' +
    'npm ERR!     /root/.npm/_logs/2021-08-23T10_41_00_344Z-debug.log\n'
```

**Workflow**

```
    semver:
        name: Semantic Versioning
        runs-on: [self-hosted, linux, x64]
        steps:
        - uses: actions/checkout@v2
        - name: Semantic Release
          id: semantic
          # https://github.com/cycjimmy/semantic-release-action
          uses: abc/semantic-release-action@master
          with:
            extra_plugins: |
              @semantic-release/exec
              @semantic-release/git
              @semantic-release/changelog
        outputs:
          new_release_published: ${{ steps.semantic.outputs.new_release_published }}
          new_release_version: ${{ steps.semantic.outputs.new_release_version }}
```

**Expected behavior**
Not fail with this error.
