### ISSUE TITLE
Command failed: npm install semantic-release

### ISSUE THREAD

**Issue by mancausoft** [cycjimmy/semantic-release-action#79]
**Describe the bug**
Today i run it and had this error:

```
Run cycjimmy/semantic-release-action@v2

added 2 packages, and audited 3 packages in 963ms

found 0 vulnerabilities


Error: Error: Command failed: npm install @semantic-release/changelog @semantic-release/git @semantic-release/exec --silent
```

**Workflow**
No change on the worklow file, was passing 3 days ago.

**Expected behavior**
Not fail like in the last months 

**Additional context**
How i can debug this?

**Comment by revolunet** [comment]
same here, any pointers ?

**Comment by revolunet** [comment]
looks like you need to add 

```yml
        with:
          semantic_version: 17
```

to your action

**Comment by mancausoft** [comment]
Thanks

**Comment by mancausoft** [comment]
@revolunet it's not fix the problem for me :(

```Run cycjimmy/semantic-release-action@v2
  with:
    branch: staging
    extra_plugins: @semantic-release/changelog
  @semantic-release/git
  @semantic-release/exec
  
    semantic_version: 17
  env:
    GITHUB_TOKEN: ***
    GH_TOKEN: ***
    GITHUB_TOKEN_NPM: ***

added 2 packages, and audited 3 packages in 966ms

found 0 vulnerabilities

Error: Error: Command failed: npm install @semantic-release/changelog @semantic-release/git @semantic-release/exec --silent
```

**Comment by pennywisdom** [comment]
i believe its the git plugin that is causing the issue. The latest version (10.0.0) has a dependency on  semantic-release@18.0.0 so it you havent fixed the plugin version then it could be throwing an error with this by trying to grab the latest version, yet all other plugins havent been updated to support (they were reporting support <= 18.0.0). I set the @semantic-release/git@9.0.1 to resolve things and work around the conflict here.

**Comment by skilbjo** [comment]
@pennywisdom I believe your fix resolves the issue I was having in #80 but for me it didn't resolve this particular issue.

what is a workaround for me was to not use `npm@7`, and to downgrade to `npm@6`

I normally have my github actions config set up like this:

```
        ...
      - uses: actions/setup-node@v2
        with:
          node-version: 14
      - run: npm install -g npm@7

      - uses: cycjimmy/semantic-release-action@v2.5.4
        ...
```

the workaround for me was:

```
        ...
      - uses: actions/setup-node@v2
        with:
          node-version: 14
      # - run: npm install -g npm@7

      - uses: cycjimmy/semantic-release-action@v2.5.4
        ...
```

which is just a workaround, not a fix...

**Comment by nicolas2mey** [comment]
Got the same error

Fixed by specifying a `setup-node` step and it works now

```yaml 
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v2.5.4
        with:
          semantic_version: 18.0.0
          extra_plugins: |
            @semantic-release/commit-analyzer@8.0.1
            @semantic-release/release-notes-generator@9.0.3
            @semantic-release/changelog@5.0.1
            @semantic-release/github@7.2.3
            @semantic-release/git@9.0.0
```

**Comment by pegiadise** [comment]
Is it actually some Node 16 breaking change that needs to be obliged?

**Comment by iamskok** [comment]
@pegiadise I don’t think it’s the reason.

This worked for me:

```
      - name: 🚀 Release
        uses: cycjimmy/semantic-release-action@v2
        id: semantic
        with:
          semantic_version: 18
          extra_plugins: |
            @semantic-release/changelog@6
            @semantic-release/git@10
            conventional-changelog-conventionalcommits@4.6.1
```

**Comment by pegiadise** [comment]
> @pegiadise I don’t think it’s the reason.
> 
> This worked for me:
> 
> ```
>       - name: 🚀 Release
>         uses: cycjimmy/semantic-release-action@v2
>         id: semantic
>         with:
>           semantic_version: 18
>           extra_plugins: |
>             @semantic-release/changelog@6
>             @semantic-release/git@10
>             conventional-changelog-conventionalcommits@4.6.1
> ```

Yup. I also ended up using semantic 18. It seems that the issue is with semantic 17 and Node 16.

**Comment by prein** [comment]
For me this error was happening due to `packages` permission missing from the job

**Comment by mirkolenz** [comment]
I faced the same issue today. For me, the problem is isolated to one repository. The main difference between my other repos where this action is used is that `actions/setup-java` is used since I intent to use `gradle-semantic-release-plugin`. I attached my release workflow at the end of this comment. I went through this entire thread and all proposed solutions did not work, I even explicitly set the versions for all packages. Is there anything I am missing?

```yaml
on:
  push:
    branches:
      - main
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "lts/*"
      - uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "adopt"
      - uses: bufbuild/buf-setup-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - uses: arduino/setup-protoc@v1
        with:
          version: "3.x"
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - uses: cycjimmy/semantic-release-action@v3
        env:
          GITHUB_TOKEN: ${{ github.token }}
          GITHUB_ACTOR: ${{ github.actor }}
          OSSRH_ACTOR: ${{ secrets.OSSRH_ACTOR }}
          OSSRH_TOKEN: ${{ secrets.OSSRH_TOKEN }}
          SIGNING_KEY: ${{ secrets.SIGNING_KEY }}
          SIGNING_PASSWORD: ${{ secrets.SIGNING_PASSWORD }}
        with:
          semantic_version: 19
          extra_plugins: |
            @semantic-release/git@10
            @semantic-release/changelog@6
            @semantic-release/exec@6
            conventional-changelog-conventionalcommits@5
            gradle-semantic-release-plugin@1
```
