### ISSUE TITLE
`4xx` back from github api when using `semantic-release/github`

### ISSUE THREAD

**Issue by skilbjo** [cycjimmy/semantic-release-action#80]
Hey @cycjimmy , thanks for your action. If you could let me know if this is an issue on my side, the `semantic-release-action` side, or a downstream breaking change with `semantic-release`

**Describe the bug**
This config used to work, it worked as recently as last Thursday (~4 days ago)

Using `@semantic-release/github` fails with a `4xx` from github: ` 'Invalid name for request "."'`

My guess is it might be related to this: https://github.com/semantic-release/github/commit/051659b290f96493e4ef5ab4948d502a7597f805

semantic-release/github now requires node@14+, but from the stack trace user-agent header below, I see:

```
 'user-agent': 'octokit-rest.js/18.10.0 octokit-core.js/3.5.1 Node.js/12.13.1 (linux; x64)',
```

I am requesting node@14 in my checkout action, so unable to explain why the user-agent header is node@12.

**Workflow**
Github action config:

```
...

      - uses: actions/setup-node@v2
        with:
          node-version: 14

      - uses: cycjimmy/semantic-release-action@v2
        id: semantic # need an `id` for output variables
        with:
          extra_plugins: |
            @semantic-release/git
            @semantic-release/changelog
            @semantic-release/exec
        env:
          GITHUB_TOKEN: ${{ secrets.ACTIONS_TOKEN }}
          NPM_TOKEN: ${{ secrets.ACTIONS_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.ACTIONS_TOKEN }}
```

.releaserc config:

```
{
  "plugins": [
    "@semantic-release/commit-analyzer",
    "@semantic-release/release-notes-generator",
    ["@semantic-release/changelog", {
      "changelogFile": "CHANGELOG.md"
    }],
    ["@semantic-release/github", {
      assets: "dist/*"
    }],
    ["@semantic-release/exec", {
      "verifyConditionsCmd": "make ci",
    }],
    ["@semantic-release/git", {
      "assets": ["CHANGELOG.md"],
      "message": "docs(release): ${nextRelease.version} [skip ci]\n\n${nextRelease.notes}"
    }]
  ]
}
````

Stack trace:

```
[2:16:29 AM] [semantic-release] › ✖  Failed step "publish" of plugin "@semantic-release/github"
[2:16:29 AM] [semantic-release] › ✖  An error occurred while running semantic-release: RequestError [HttpError]: Invalid name for request "."
    at /home/runner/work/_actions/cycjimmy/semantic-release-action/v2/node_modules/@octokit/request/dist-node/index.js:86:21
    at processTicksAndRejections (internal/process/task_queues.js:93:5) {
  name: 'HttpError',
  status: 400,
  response: {
    url: 'https://uploads.github.com/repos/[redacted]/[redacted]/releases/49951210/assets?name=canary-types.js&',
    status: 400,
    headers: {
      'cache-control': 'no-cache',
      connection: 'close',
      'content-length': '92',
      'content-security-policy': "default-src 'none'",
      'content-type': 'application/json; charset=utf-8',
      date: 'Tue, 21 Sep 2021 02:16:29 GMT',
      'strict-transport-security': 'max-age=31557600',
      'x-content-type-options': 'nosniff',
      'x-frame-options': 'deny',
      'x-github-request-id': '0840:16E2:1030B9:150FEA:6140007D',
      'x-xss-protection': '1; mode=block'
    },
    data: {
      message: 'Invalid name for request "."',
      request_id: '0840:16E2:1030B9:150FEA:6140007D',
    }
  },
  request: {
    method: 'POST',
    url: 'https://uploads.github.com/repos/[redacted]/[redacted]/releases/49951210/assets?name=canary-types.js&',
    headers: {
      accept: 'application/vnd.github.v3+json',
      'user-agent': 'octokit-rest.js/18.10.0 octokit-core.js/3.5.1 Node.js/12.13.1 (linux; x64)',
      'content-type': 'application/javascript',
      'content-length': 403,
      authorization: 'token [REDACTED]'
    },
    body: <Buffer ...... 353 more bytes>,
    request: { agent: undefined, hook: [Function: bound bound register] }
  },
  pluginName: '@semantic-release/github'
}
Error: HttpError: Invalid name for request "."
```

**Expected behavior**
No `4xx` error from github when using the below config

**Additional context**
