### ISSUE TITLE
missing v2 tag

### ISSUE THREAD

**Issue by portellaa** [cycjimmy/semantic-release-action#89]
**Describe the bug**
it looks like the tag v2 disappeared

**Workflow**
```yaml
- uses: cycjimmy/semantic-release-action@v2
   id: semantic
   env:
     GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
   with:
     dry_run: true
```

**Expected behavior**
It used to run just using v2 tag
