### ISSUE TITLE
How to remove npm plugin

### ISSUE THREAD

**Issue by paulpach** [cycjimmy/semantic-release-action#9]
I want to use semantic-release for a non npm based project.  How do I remove npm plugin?

**Comment by cycjimmy** [comment]
You can set the `npmPublish` attribute to `false` of `@semantic-release/npm` plugin in your semantic-release configuration.

```javascript
{
  "plugins": [
    ...
    ["@semantic-release/npm", {
      "npmPublish": false,
    }],
    ...
  ]
}
```

**Comment by sudkumar** [comment]
@cycjimmy I think, setting `npmPublish: false` only disabled `npm release` step but it will still try to update the `package.json:version` field. I may be wrong but I'm using this option to disable the npm publish and still updating the version field in my package.json file.

@paulpach If the above solution doesn't work for you, just remove the `@semantic-release/npm` from plugins array:

```diff
plugins: [
  "@semantic-release/commit-analyzer",
  "@semantic-release/github",
- "@semantic-release/npm",
  "@semantic-release/release-notes-generator",
]
```

> P.S.: To disable any plugin, just remove it from the list. [docs](https://semantic-release.gitbook.io/semantic-release/usage/configuration)

**Comment by cycjimmy** [comment]
The issue is inactive for a long time. I will close it.

**Comment by gimyboya** [comment]
@sudkumar  @cycjimmy I have removed the npm plugin from the list and somehow i keep being asked about the npm token. here is my `.releaserc` file:
```json
{
  "release": {
    "branches": ["master", "next"],
    "plugins": ['@semantic-release/commit-analyzer', '@semantic-release/release-notes-generator', '@semantic-release/github']
  }
}
```

**Comment by sudkumar** [comment]
@gimyboya  Just add a fake `NPM_TOKEN` environment variable with a random value e.g. 000000000000000 to your action

You can checkout [this repository](https://github.com/craftsys/msg91-laravel) for reference where I am using this action for PHP package releases. Here are some snippets for quick reference.

**[.releaserc.json](https://github.com/craftsys/msg91-laravel/blob/master/.releaserc.json)**
```
{
    "plugins": [
        "@semantic-release/commit-analyzer",
        "@semantic-release/release-notes-generator",
        "@semantic-release/github"
    ]
}
```

**[release.yml](https://github.com/craftsys/msg91-laravel/blob/master/.github/workflows/release.yml)**
```yml
name: New Release

on:
  push:
    branches: [ master ]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: New Release
        uses: cycjimmy/semantic-release-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: 000000000000000
        with:
          extra_plugins: |
            @semantic-release/git
            @semantic-release/changelog
```

---

Hope it helps. 🍻
