### ISSUE TITLE
Does not support configured Node.js version

### ISSUE THREAD

**Issue by kettanaito** [cycjimmy/semantic-release-action#96]
**Describe the bug**

Semantic release action disregards the Node.js version previously configured in the same job. 

**Workflow**

- [Failed workflow example](https://github.com/mswjs/interceptors/runs/5390962941?check_suite_focus=true)

**Expected behavior**

Semantic release must execute itself and any sub-commands using the globally available Node.js version (in the case above `16.14.0`, not `12.13.1`). 

**Additional context**
Looks like it fallbacks to some default Node.js version but I see no options to disable this fallback. 

```yml
name: release
on:
  schedule:
    - cron: '0 23 * * *'
  workflow_dispatch:
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          # Explicitly setting an LTS version of Node.js
          node-version: 16.14.0

      - name: Install dependencies
        uses: bahmutov/npm-install@v1

      - name: Build
        run: yarn build

      - name: Test
        run: yarn test

      - name: Release
        # This will still use Node.js 12.13.1
        uses: cycjimmy/semantic-release-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
```
